# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Agni Mantra
subtitle: "Swami Vivekananda (स्वामी विवेकानंद)"
email: roopkt@gmail.com
description: महाशक्ति का तुममें संचार होगा - कदापि भय भीत मत होना। पवित्र होओ, विश्वासी होओ, और आज्ञापालक होओ।
twitter_username: "rupeshtiwari_co"
github_username: rupeshtiwari
minimal_mistakes_skin: default
url: "https://rupeshtiwari.com"
baseurl: "/vivekananda"
search: true
logo: "/assets/images/logo.jpg"

# Change the repository name
repository: "rupeshtiwari/vivekananda" 

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Rupesh Tiwari"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "स्वामी विवेकानंद मेरे आत्मा में!"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "fullstackmaster1@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "http://twitter.com/rupeshtiwari_co"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/roopkt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rupesh-tiwari"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/rupeshtiwari"

footer:
  links:
    - label: "Rupesh Tiwari"
      icon: "fas fa-registered"
      url: "https://www.rupeshtiwari.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/roopkt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rupesh-tiwari"
   

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
    shortname: "https-www-rupeshtiwari-com-vivekananda"

teaser: "/assets/images/logo.jpg"
